### ISSUE TITLE
node-canvas-api can't add issues to the LA project board

### ISSUE THREAD

**Issue by craigdsthompson** [ubc/node-canvas-api#57]
This repo doesn't have access to the `ADD_TO_PROJECT_LA` organization secret. This needs to be configured in the UBC organization settings: https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#reviewing-access-to-organization-level-secrets

```
Run actions/add-to-project@v0.3.0
  with:
    project-url: https://github.com/orgs/ubc/projects/7
Error: Input required and not supplied: github-token
```

**Comment by jlongland** [comment]
Added this repo to have access to `ADD_TO_PROJECT_LA`

**Comment by craigdsthompson** [comment]
@jlongland I think something further is needed to fix this. The add-to-project action is still failing and I don't see the `ADD_TO_PROJECT_LA` secret listed under the Organization secrets for this repo.

**Comment by jlongland** [comment]
@craigdsthompson Try now. It was showing 47 repos selected, but now says 48 repos selected. Maybe I didn't hit `Save Changes`?

**Comment by craigdsthompson** [comment]
Works now, thanks Jeff
