### ISSUE TITLE
prompts should not be a dependency

### ISSUE THREAD

**Issue by craigdsthompson** [ubc/node-canvas-api#62]
The `prompts` package is a dependency for `jest-cli`, which a dependency for `jest` (which is a devDependency of this project).

https://github.com/ubc/node-canvas-api/blob/43f5e6e56c5a46cda5ca006796686da01e2f6a00/package.json#L25

`prompts` is not used directly in `node-canvas-api`, so I think it can safely be removed from the dependencies in `package.json`. `package-lock.json` will still contain `prompts` as a resolved dependency from `jest`.

**Comment by justin0022** [comment]
Resolved in https://github.com/ubc/node-canvas-api/pull/66
