### ISSUE TITLE
request does not need to be a dependency

### ISSUE THREAD

**Issue by craigdsthompson** [ubc/node-canvas-api#63]
The request package is not used directly by `node-canvas-api`. It's a peerDependency of `request-promise`, so we can remove it from `package.json` and let npm sort of the dependencies for `package-lock.json`

https://github.com/ubc/node-canvas-api/blob/43f5e6e56c5a46cda5ca006796686da01e2f6a00/package.json#L27

**Comment by justin0022** [comment]
Resolved in https://github.com/ubc/node-canvas-api/pull/66
